name: Syntax Tests Branch
# https://github.com/sublimetext/syntax-test-action

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

jobs:
  syntax_tests:
    name: Syntax Tests Branch (${{ matrix.build }})
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        include:
          - build: 'latest'
          # - build: 3211  # libgl1-mesa-glx is not available on ubuntu-latest SublimeText/syntax-action#17
    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'axemonk/Excel-formula/tree/axemonk-patch-1'
      - uses: SublimeText/syntax-test-action@v2
        with:
          build: ${{ matrix.build }}
          package_name: 'Excel formula'
